{-# LANGUAGE MagicHash #-}

module Example.Shaders where

import           Control.Exception
import           Data.Word
import           Foreign.Marshal.Alloc
import           Foreign.Marshal.Array
import           GHC.Ptr
import           System.IO



-- | Helper function for copy-pasting files into this module.
extractRawShader :: FilePath -> IO (Int, String)
extractRawShader file = do
  bracket (openBinaryFile file ReadMode) hClose $ \h -> do
    len <- hFileSize h
    allocaBytes (fromIntegral len) $ \ptr -> do
      _ <- hGetBuf h ptr $ fromIntegral len
      raw <- peekArray (fromIntegral len) (ptr :: Ptr Word8)
      return (fromIntegral len, toEnum . fromIntegral <$> raw)



vertexShaderSize :: Num a => a
vertexShaderSize = 1008

-- #version 450
--
-- layout(location = 0) in vec2 inPosition;
-- layout(location = 1) in vec3 inColor;
--
-- layout(location = 0) out vec3 fragColor;
--
-- void main() {
--     gl_Position = vec4(inPosition, 0.0, 1.0);
--     fragColor = inColor;
-- }
vertexShaderData :: Ptr Word32
vertexShaderData =
  Ptr "\ETX\STX#\a\NUL\NUL\SOH\NUL\v\NUL\b\NUL!\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC1\NUL\STX\NUL\SOH\NUL\NUL\NUL\v\NUL\ACK\NUL\SOH\NUL\NUL\NULGLSL.std.450\NUL\NUL\NUL\NUL\SO\NUL\ETX\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\SI\NUL\t\NUL\NUL\NUL\NUL\NUL\EOT\NUL\NUL\NULmain\NUL\NUL\NUL\NUL\r\NUL\NUL\NUL\DC2\NUL\NUL\NUL\GS\NUL\NUL\NUL\US\NUL\NUL\NUL\ETX\NUL\ETX\NUL\STX\NUL\NUL\NUL\194\SOH\NUL\NUL\ENQ\NUL\EOT\NUL\EOT\NUL\NUL\NULmain\NUL\NUL\NUL\NUL\ENQ\NUL\ACK\NUL\v\NUL\NUL\NULgl_PerVertex\NUL\NUL\NUL\NUL\ACK\NUL\ACK\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NULgl_Position\NUL\ACK\NUL\a\NUL\v\NUL\NUL\NUL\SOH\NUL\NUL\NULgl_PointSize\NUL\NUL\NUL\NUL\ACK\NUL\a\NUL\v\NUL\NUL\NUL\STX\NUL\NUL\NULgl_ClipDistance\NUL\ACK\NUL\a\NUL\v\NUL\NUL\NUL\ETX\NUL\NUL\NULgl_CullDistance\NUL\ENQ\NUL\ETX\NUL\r\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ENQ\NUL\ENQ\NUL\DC2\NUL\NUL\NULinPosition\NUL\NUL\ENQ\NUL\ENQ\NUL\GS\NUL\NUL\NULfragColor\NUL\NUL\NUL\ENQ\NUL\EOT\NUL\US\NUL\NUL\NULinColor\NULH\NUL\ENQ\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NUL\v\NUL\NUL\NUL\NUL\NUL\NUL\NULH\NUL\ENQ\NUL\v\NUL\NUL\NUL\SOH\NUL\NUL\NUL\v\NUL\NUL\NUL\SOH\NUL\NUL\NULH\NUL\ENQ\NUL\v\NUL\NUL\NUL\STX\NUL\NUL\NUL\v\NUL\NUL\NUL\ETX\NUL\NUL\NULH\NUL\ENQ\NUL\v\NUL\NUL\NUL\ETX\NUL\NUL\NUL\v\NUL\NUL\NUL\EOT\NUL\NUL\NULG\NUL\ETX\NUL\v\NUL\NUL\NUL\STX\NUL\NUL\NULG\NUL\EOT\NUL\DC2\NUL\NUL\NUL\RS\NUL\NUL\NUL\NUL\NUL\NUL\NULG\NUL\EOT\NUL\GS\NUL\NUL\NUL\RS\NUL\NUL\NUL\NUL\NUL\NUL\NULG\NUL\EOT\NUL\US\NUL\NUL\NUL\RS\NUL\NUL\NUL\SOH\NUL\NUL\NUL\DC3\NUL\STX\NUL\STX\NUL\NUL\NUL!\NUL\ETX\NUL\ETX\NUL\NUL\NUL\STX\NUL\NUL\NUL\SYN\NUL\ETX\NUL\ACK\NUL\NUL\NUL \NUL\NUL\NUL\ETB\NUL\EOT\NUL\a\NUL\NUL\NUL\ACK\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NAK\NUL\EOT\NUL\b\NUL\NUL\NUL \NUL\NUL\NUL\NUL\NUL\NUL\NUL+\NUL\EOT\NUL\b\NUL\NUL\NUL\t\NUL\NUL\NUL\SOH\NUL\NUL\NUL\FS\NUL\EOT\NUL\n\NUL\NUL\NUL\ACK\NUL\NUL\NUL\t\NUL\NUL\NUL\RS\NUL\ACK\NUL\v\NUL\NUL\NUL\a\NUL\NUL\NUL\ACK\NUL\NUL\NUL\n\NUL\NUL\NUL\n\NUL\NUL\NUL \NUL\EOT\NUL\f\NUL\NUL\NUL\ETX\NUL\NUL\NUL\v\NUL\NUL\NUL;\NUL\EOT\NUL\f\NUL\NUL\NUL\r\NUL\NUL\NUL\ETX\NUL\NUL\NUL\NAK\NUL\EOT\NUL\SO\NUL\NUL\NUL \NUL\NUL\NUL\SOH\NUL\NUL\NUL+\NUL\EOT\NUL\SO\NUL\NUL\NUL\SI\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETB\NUL\EOT\NUL\DLE\NUL\NUL\NUL\ACK\NUL\NUL\NUL\STX\NUL\NUL\NUL \NUL\EOT\NUL\DC1\NUL\NUL\NUL\SOH\NUL\NUL\NUL\DLE\NUL\NUL\NUL;\NUL\EOT\NUL\DC1\NUL\NUL\NUL\DC2\NUL\NUL\NUL\SOH\NUL\NUL\NUL+\NUL\EOT\NUL\ACK\NUL\NUL\NUL\DC4\NUL\NUL\NUL\NUL\NUL\NUL\NUL+\NUL\EOT\NUL\ACK\NUL\NUL\NUL\NAK\NUL\NUL\NUL\NUL\NUL\128? \NUL\EOT\NUL\EM\NUL\NUL\NUL\ETX\NUL\NUL\NUL\a\NUL\NUL\NUL\ETB\NUL\EOT\NUL\ESC\NUL\NUL\NUL\ACK\NUL\NUL\NUL\ETX\NUL\NUL\NUL \NUL\EOT\NUL\FS\NUL\NUL\NUL\ETX\NUL\NUL\NUL\ESC\NUL\NUL\NUL;\NUL\EOT\NUL\FS\NUL\NUL\NUL\GS\NUL\NUL\NUL\ETX\NUL\NUL\NUL \NUL\EOT\NUL\RS\NUL\NUL\NUL\SOH\NUL\NUL\NUL\ESC\NUL\NUL\NUL;\NUL\EOT\NUL\RS\NUL\NUL\NUL\US\NUL\NUL\NUL\SOH\NUL\NUL\NUL6\NUL\ENQ\NUL\STX\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETX\NUL\NUL\NUL\248\NUL\STX\NUL\ENQ\NUL\NUL\NUL=\NUL\EOT\NUL\DLE\NUL\NUL\NUL\DC3\NUL\NUL\NUL\DC2\NUL\NUL\NULQ\NUL\ENQ\NUL\ACK\NUL\NUL\NUL\SYN\NUL\NUL\NUL\DC3\NUL\NUL\NUL\NUL\NUL\NUL\NULQ\NUL\ENQ\NUL\ACK\NUL\NUL\NUL\ETB\NUL\NUL\NUL\DC3\NUL\NUL\NUL\SOH\NUL\NUL\NULP\NUL\a\NUL\a\NUL\NUL\NUL\CAN\NUL\NUL\NUL\SYN\NUL\NUL\NUL\ETB\NUL\NUL\NUL\DC4\NUL\NUL\NUL\NAK\NUL\NUL\NULA\NUL\ENQ\NUL\EM\NUL\NUL\NUL\SUB\NUL\NUL\NUL\r\NUL\NUL\NUL\SI\NUL\NUL\NUL>\NUL\ETX\NUL\SUB\NUL\NUL\NUL\CAN\NUL\NUL\NUL=\NUL\EOT\NUL\ESC\NUL\NUL\NUL \NUL\NUL\NUL\US\NUL\NUL\NUL>\NUL\ETX\NUL\GS\NUL\NUL\NUL \NUL\NUL\NUL\253\NUL\SOH\NUL8\NUL\SOH\NUL"#



fragmentShaderSize :: Num a => a
fragmentShaderSize = 500

-- #version 450
--
-- layout(location = 0) in vec3 fragColor;
--
-- layout(location = 0) out vec4 outColor;
--
-- void main() {
--     outColor = vec4(fragColor, 1.0);
-- }
fragmentShaderData :: Ptr Word32
fragmentShaderData =
  Ptr "\ETX\STX#\a\NUL\NUL\SOH\NUL\v\NUL\b\NUL\DC3\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC1\NUL\STX\NUL\SOH\NUL\NUL\NUL\v\NUL\ACK\NUL\SOH\NUL\NUL\NULGLSL.std.450\NUL\NUL\NUL\NUL\SO\NUL\ETX\NUL\NUL\NUL\NUL\NUL\SOH\NUL\NUL\NUL\SI\NUL\a\NUL\EOT\NUL\NUL\NUL\EOT\NUL\NUL\NULmain\NUL\NUL\NUL\NUL\t\NUL\NUL\NUL\f\NUL\NUL\NUL\DLE\NUL\ETX\NUL\EOT\NUL\NUL\NUL\a\NUL\NUL\NUL\ETX\NUL\ETX\NUL\STX\NUL\NUL\NUL\194\SOH\NUL\NUL\ENQ\NUL\EOT\NUL\EOT\NUL\NUL\NULmain\NUL\NUL\NUL\NUL\ENQ\NUL\ENQ\NUL\t\NUL\NUL\NULoutColor\NUL\NUL\NUL\NUL\ENQ\NUL\ENQ\NUL\f\NUL\NUL\NULfragColor\NUL\NUL\NULG\NUL\EOT\NUL\t\NUL\NUL\NUL\RS\NUL\NUL\NUL\NUL\NUL\NUL\NULG\NUL\EOT\NUL\f\NUL\NUL\NUL\RS\NUL\NUL\NUL\NUL\NUL\NUL\NUL\DC3\NUL\STX\NUL\STX\NUL\NUL\NUL!\NUL\ETX\NUL\ETX\NUL\NUL\NUL\STX\NUL\NUL\NUL\SYN\NUL\ETX\NUL\ACK\NUL\NUL\NUL \NUL\NUL\NUL\ETB\NUL\EOT\NUL\a\NUL\NUL\NUL\ACK\NUL\NUL\NUL\EOT\NUL\NUL\NUL \NUL\EOT\NUL\b\NUL\NUL\NUL\ETX\NUL\NUL\NUL\a\NUL\NUL\NUL;\NUL\EOT\NUL\b\NUL\NUL\NUL\t\NUL\NUL\NUL\ETX\NUL\NUL\NUL\ETB\NUL\EOT\NUL\n\NUL\NUL\NUL\ACK\NUL\NUL\NUL\ETX\NUL\NUL\NUL \NUL\EOT\NUL\v\NUL\NUL\NUL\SOH\NUL\NUL\NUL\n\NUL\NUL\NUL;\NUL\EOT\NUL\v\NUL\NUL\NUL\f\NUL\NUL\NUL\SOH\NUL\NUL\NUL+\NUL\EOT\NUL\ACK\NUL\NUL\NUL\SO\NUL\NUL\NUL\NUL\NUL\128?6\NUL\ENQ\NUL\STX\NUL\NUL\NUL\EOT\NUL\NUL\NUL\NUL\NUL\NUL\NUL\ETX\NUL\NUL\NUL\248\NUL\STX\NUL\ENQ\NUL\NUL\NUL=\NUL\EOT\NUL\n\NUL\NUL\NUL\r\NUL\NUL\NUL\f\NUL\NUL\NULQ\NUL\ENQ\NUL\ACK\NUL\NUL\NUL\SI\NUL\NUL\NUL\r\NUL\NUL\NUL\NUL\NUL\NUL\NULQ\NUL\ENQ\NUL\ACK\NUL\NUL\NUL\DLE\NUL\NUL\NUL\r\NUL\NUL\NUL\SOH\NUL\NUL\NULQ\NUL\ENQ\NUL\ACK\NUL\NUL\NUL\DC1\NUL\NUL\NUL\r\NUL\NUL\NUL\STX\NUL\NUL\NULP\NUL\a\NUL\a\NUL\NUL\NUL\DC2\NUL\NUL\NUL\SI\NUL\NUL\NUL\DLE\NUL\NUL\NUL\DC1\NUL\NUL\NUL\SO\NUL\NUL\NUL>\NUL\ETX\NUL\t\NUL\NUL\NUL\DC2\NUL\NUL\NUL\253\NUL\SOH\NUL8\NUL\SOH\NUL"#
