version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build-arm64:
    machine:
      image: ubuntu-2204:current
    resource_class: arm.medium
    steps:
      - checkout
      - restore_cache:
          name: Restore
          key: arm64-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
      - run:
          name: Install GHC
          command: |
            sudo apt-get update
            sudo NEEDRESTART_MODE=a apt-get install -y libgl-dev libvulkan-dev xorg-dev

            curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

            PATH=$HOME/.ghcup/bin:$PATH

            ghcup install cabal 3.6.2.0
            ghcup set cabal 3.6.2.0

            ghcup install ghc 9.2.5
            ghcup set ghc 9.2.5

      - run:
          name: Update Dependencies
          command: |
            PATH=$HOME/.ghcup/bin:$PATH

            cabal new-update

      - run:
          name: Build
          command: |
            PATH=$HOME/.ghcup/bin:$PATH

            mkdir /tmp/out
            cd vulkan-example
            cabal new-install --install-method=copy --installdir=/tmp/out --enable-executable-stripping exe:vulkan-example

      - save_cache:
          name: Cache
          key: arm64-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
          paths:
            - "/root/.cabal"
            - "dist-newstyle"

      - store_artifacts:
          path: /tmp/out/vulkan-example

  build-linux:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    parameters:
      version:
        type: string
      keep-artifact:
        type: boolean
    steps:
      - checkout
      - restore_cache:
          name: Restore
          key: linux-<< parameters.version >>-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
      - run:
          name: Install GHC
          command: |
            sudo apt-get update
            sudo NEEDRESTART_MODE=a apt-get install -y libgl-dev libvulkan-dev xorg-dev

            curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

            PATH=$HOME/.ghcup/bin:$PATH

            ghcup install cabal 3.6.2.0
            ghcup set cabal 3.6.2.0

            ghcup install ghc << parameters.version >>
            ghcup set ghc << parameters.version >>

      - run:
          name: Update Dependencies
          command: |
            PATH=$HOME/.ghcup/bin:$PATH

            cabal new-update

      - run:
          name: Build
          command: |
            PATH=$HOME/.ghcup/bin:$PATH

            mkdir /tmp/out
            cd vulkan-example
            cabal new-install --install-method=copy --installdir=/tmp/out --enable-executable-stripping exe:vulkan-example

      - save_cache:
          name: Cache
          key: linux-<< parameters.version >>-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
          paths:
            - "/root/.cabal"
            - "dist-newstyle"

      - when:
          condition: << parameters.keep-artifact >>
          steps:
            - store_artifacts:
                path: /tmp/out/vulkan-example



  build-windows:
    executor: win/default
    steps:
      - checkout
      - restore_cache:
          name: Restore
          key: windows-9.2.6-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
      - run:
          name: Install GHC
          shell: bash.exe
          command: |
            curl --proto '=https' --tlsv1.2 -sSf https://sdk.lunarg.com/sdk/download/1.3.239.0/windows/VulkanSDK-1.3.239.0-Installer.exe --output "$TEMP/vulkan-sdk.exe"

            "$TEMP/vulkan-sdk.exe" --root "/C/VulkanSDK" --accept-licenses --default-answer --confirm-command install

            curl --proto '=https' --tlsv1.2 -sSf https://sdk.lunarg.com/sdk/download/1.3.239.0/windows/VulkanRT-1.3.239.0-Components.zip --output "$TEMP/vulkan-components.zip"

            unzip -d "$TEMP" "$TEMP/vulkan-components.zip"

            LD_LIBRARY_PATH="$TEMP/VulkanRT-1.3.239.0-Components/x64/" /C/VulkanSDK/Bin/vulkaninfoSDK.exe

            curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | BOOTSTRAP_HASKELL_NONINTERACTIVE=1 BOOTSTRAP_HASKELL_MINIMAL=1 sh

            PATH=/C/ghcup/bin:$PATH

            ghcup install cabal 3.6.2.0
            ghcup set cabal 3.6.2.0

            ghcup install ghc 9.2.6
            ghcup set ghc 9.2.6

            echo 'export PATH=/C/ghcup/ghc/9.2.6/mingw/x86_64-w64-mingw32/bin:/C/ghcup/ghc/9.2.6/mingw/lib/gcc/x86_64-w64-mingw32/10.2.0:/C/ghcup/bin:/C/ghcup/ghc/9.2.6/mingw/bin:/C/VulkanSDK/Bin:$PATH' >> $BASH_ENV

      - run:
          name: Update Dependencies
          shell: bash.exe
          command: |
            cabal new-update

      - run:
          name: Build
          shell: bash.exe
          command: |
            if [ -f cc1 ]; then echo 'cc1 exists'; else echo 'no cc1'; fi
            if [ -f cc1plus ]; then echo 'cc1plus exists'; else echo 'no cc1'; fi
            mkdir $TEMP/out
            cd vulkan-example
            cabal new-install -j1 -v3 --ghc-options='-v' --install-method=copy --installdir="$TEMP/out" --enable-executable-stripping exe:vulkan-example

          no_output_timeout: 59m

#     - save_cache:
#         name: Cache
#         key: windows-9.2.5-{{ checksum "vulkan-raw/vulkan-raw.cabal" }}
#         paths:
#           - "%APPDATA%\cabal"
#           - "dist-newstyle"

      - store_artifacts:
          path: $TEMP/out/vulkan-example.exe


workflows:
  workflow:
    jobs:
#     - build-arm64:
#         name: aarch64-9.2.5
#     - build-linux:
#         name: linux-8.4.4
#         version: 8.4.4
#         keep-artifact: false
#     - build-linux:
#         name: linux-8.6.5
#         version: 8.6.5
#         keep-artifact: false
#     - build-linux:
#         name: linux-8.8.4
#         version: 8.8.4
#         keep-artifact: false
#     - build-linux:
#         name: linux-8.10.7
#         version: 8.10.7
#         keep-artifact: false
#     - build-linux:
#         name: linux-9.0.2
#         version: 9.0.2
#         keep-artifact: false
#     - build-linux:
#         name: linux-9.2.5
#         version: 9.2.5
#         keep-artifact: true
      - build-windows:
          name: windows-9.2.6
