#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkDescriptorPoolInlineUniformBlockCreateInfoEXT where

import Vulkan.Types.Struct.VkDescriptorPoolInlineUniformBlockCreateInfo



type VkDescriptorPoolInlineUniformBlockCreateInfoEXT = VkDescriptorPoolInlineUniformBlockCreateInfo