#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkDescriptorSetVariableDescriptorCountAllocateInfoEXT where

import Vulkan.Types.Struct.VkDescriptorSetVariableDescriptorCountAllocateInfo



type VkDescriptorSetVariableDescriptorCountAllocateInfoEXT = VkDescriptorSetVariableDescriptorCountAllocateInfo