#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceShaderSubgroupExtendedTypesFeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures



type VkPhysicalDeviceShaderSubgroupExtendedTypesFeaturesKHR = VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures