#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceDescriptorIndexingPropertiesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceDescriptorIndexingProperties



type VkPhysicalDeviceDescriptorIndexingPropertiesEXT = VkPhysicalDeviceDescriptorIndexingProperties