#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceSamplerFilterMinmaxProperties



type VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT = VkPhysicalDeviceSamplerFilterMinmaxProperties