#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceShaderFloat16Int8FeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceShaderFloat16Int8Features



type VkPhysicalDeviceShaderFloat16Int8FeaturesKHR = VkPhysicalDeviceShaderFloat16Int8Features