#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceShaderTerminateInvocationFeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceShaderTerminateInvocationFeatures



type VkPhysicalDeviceShaderTerminateInvocationFeaturesKHR = VkPhysicalDeviceShaderTerminateInvocationFeatures