#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures



type VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT = VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures