#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceDescriptorIndexingFeaturesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceDescriptorIndexingFeatures



type VkPhysicalDeviceDescriptorIndexingFeaturesEXT = VkPhysicalDeviceDescriptorIndexingFeatures