#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceSamplerYcbcrConversionFeatures



type VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR = VkPhysicalDeviceSamplerYcbcrConversionFeatures