#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceTextureCompressionASTCHDRFeatures



type VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT = VkPhysicalDeviceTextureCompressionASTCHDRFeatures