#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceVulkanMemoryModelFeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceVulkanMemoryModelFeatures



type VkPhysicalDeviceVulkanMemoryModelFeaturesKHR = VkPhysicalDeviceVulkanMemoryModelFeatures