#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceSeparateDepthStencilLayoutsFeaturesKHR where

import Vulkan.Types.Struct.VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures



type VkPhysicalDeviceSeparateDepthStencilLayoutsFeaturesKHR = VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures