#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceSubgroupSizeControlPropertiesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceSubgroupSizeControlProperties



type VkPhysicalDeviceSubgroupSizeControlPropertiesEXT = VkPhysicalDeviceSubgroupSizeControlProperties