#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceInlineUniformBlockPropertiesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceInlineUniformBlockProperties



type VkPhysicalDeviceInlineUniformBlockPropertiesEXT = VkPhysicalDeviceInlineUniformBlockProperties