#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkPhysicalDeviceTexelBufferAlignmentPropertiesEXT where

import Vulkan.Types.Struct.VkPhysicalDeviceTexelBufferAlignmentProperties



type VkPhysicalDeviceTexelBufferAlignmentPropertiesEXT = VkPhysicalDeviceTexelBufferAlignmentProperties