#include <vulkan/vulkan.h>

module Vulkan.Types.Struct.VkRenderPassInputAttachmentAspectCreateInfoKHR where

import Vulkan.Types.Struct.VkRenderPassInputAttachmentAspectCreateInfo



type VkRenderPassInputAttachmentAspectCreateInfoKHR = VkRenderPassInputAttachmentAspectCreateInfo