{-# LANGUAGE CPP #-}
{-# LANGUAGE PatternSynonyms #-}

#include <vulkan/vulkan.h>

module Vulkan.Types.Enum.VkBuildAccelerationStructureFlagBitsKHR where

import Vulkan.Types.Base



#if VK_KHR_acceleration_structure
type VkBuildAccelerationStructureFlagBitsKHR = VkFlags
#endif

#if VK_KHR_acceleration_structure
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR = 1
#endif

#if VK_KHR_acceleration_structure
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR = 2
#endif

#if VK_KHR_acceleration_structure
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR = 4
#endif

#if VK_KHR_acceleration_structure
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR = 8
#endif

#if VK_KHR_acceleration_structure
pattern VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR = 16
#endif

#if VK_NV_ray_tracing
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_NV = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_UPDATE_BIT_KHR
#endif

#if VK_NV_ray_tracing
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_NV = VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_COMPACTION_BIT_KHR
#endif

#if VK_NV_ray_tracing
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_NV = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_TRACE_BIT_KHR
#endif

#if VK_NV_ray_tracing
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_NV = VK_BUILD_ACCELERATION_STRUCTURE_PREFER_FAST_BUILD_BIT_KHR
#endif

#if VK_NV_ray_tracing
pattern VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_NV = VK_BUILD_ACCELERATION_STRUCTURE_LOW_MEMORY_BIT_KHR
#endif

#if VK_NV_ray_tracing_motion_blur
pattern VK_BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_MOTION_BIT_NV = 32
#endif

#if VK_EXT_opacity_micromap
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_EXT :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_UPDATE_EXT = 64
#endif

#if VK_EXT_opacity_micromap
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_EXT :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_DISABLE_OPACITY_MICROMAPS_EXT = 128
#endif

#if VK_EXT_opacity_micromap
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_EXT :: (Eq a, Num a) => a
pattern VK_BUILD_ACCELERATION_STRUCTURE_ALLOW_OPACITY_MICROMAP_DATA_UPDATE_EXT = 256
#endif