{-# LANGUAGE CPP #-}
{-# LANGUAGE PatternSynonyms #-}

#include <vulkan/vulkan.h>

module Vulkan.Types.Enum.VkDescriptorBindingFlagBits where

import Vulkan.Types.Base



#if VK_VERSION_1_2
type VkDescriptorBindingFlagBits = VkFlags
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT = 1
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT = 2
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT = 4
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT = 8
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_UPDATE_AFTER_BIND_BIT_EXT = 1
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_UPDATE_UNUSED_WHILE_PENDING_BIT_EXT = 2
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_PARTIALLY_BOUND_BIT_EXT = 4
#endif

#if VK_VERSION_1_2
pattern VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT :: (Eq a, Num a) => a
pattern VK_DESCRIPTOR_BINDING_VARIABLE_DESCRIPTOR_COUNT_BIT_EXT = 8
#endif