{-# LANGUAGE CPP #-}
{-# LANGUAGE PatternSynonyms #-}

#include <vulkan/vulkan.h>

module Vulkan.Types.Enum.VkPrimitiveTopology where

import Data.Int



type VkPrimitiveTopology = #{type int}

pattern VK_PRIMITIVE_TOPOLOGY_POINT_LIST :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_POINT_LIST = 0

pattern VK_PRIMITIVE_TOPOLOGY_LINE_LIST :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_LINE_LIST = 1

pattern VK_PRIMITIVE_TOPOLOGY_LINE_STRIP :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_LINE_STRIP = 2

pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST = 3

pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP = 4

pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN = 5

pattern VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY = 6

pattern VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY = 7

pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY = 8

pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY = 9

pattern VK_PRIMITIVE_TOPOLOGY_PATCH_LIST :: (Eq a, Num a) => a
pattern VK_PRIMITIVE_TOPOLOGY_PATCH_LIST = 10