{-# LANGUAGE CPP #-}
{-# LANGUAGE PatternSynonyms #-}

#include <vulkan/vulkan.h>

module Vulkan.Types.Enum.VkSubpassDescriptionFlagBits where

import Vulkan.Types.Base



type VkSubpassDescriptionFlagBits = VkFlags

#if VK_NVX_multiview_per_view_attributes
pattern VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_PER_VIEW_ATTRIBUTES_BIT_NVX = 1
#endif

#if VK_NVX_multiview_per_view_attributes
pattern VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_PER_VIEW_POSITION_X_ONLY_BIT_NVX = 2
#endif

#if VK_QCOM_render_pass_shader_resolve
pattern VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_FRAGMENT_REGION_BIT_QCOM = 4
#endif

#if VK_QCOM_render_pass_shader_resolve
pattern VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_SHADER_RESOLVE_BIT_QCOM = 8
#endif

#if VK_ARM_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_ARM :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_ARM = 16
#endif

#if VK_ARM_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_ARM :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_ARM = 32
#endif

#if VK_ARM_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_ARM :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_ARM = 64
#endif

#if VK_EXT_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_EXT :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_COLOR_ACCESS_BIT_EXT = 16
#endif

#if VK_EXT_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_EXT :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_DEPTH_ACCESS_BIT_EXT = 32
#endif

#if VK_EXT_rasterization_order_attachment_access
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_EXT :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_RASTERIZATION_ORDER_ATTACHMENT_STENCIL_ACCESS_BIT_EXT = 64
#endif

#if VK_EXT_legacy_dithering
pattern VK_SUBPASS_DESCRIPTION_ENABLE_LEGACY_DITHERING_BIT_EXT :: (Eq a, Num a) => a
pattern VK_SUBPASS_DESCRIPTION_ENABLE_LEGACY_DITHERING_BIT_EXT = 128
#endif